Added our psul global vars
psu-libraries/psulib_base pull request #15
Opened 2024-02-14 21:30 UTC by schwent

2024-02-15 13:20 UTC, whereismyjetpack commented
I think we'll want to add this into `webpack.mix.js` to get compiled at build time.

2024-02-15 13:20 UTC, whereismyjetpack requested changes

2024-02-15 13:20 UTC, whereismyjetpack commented on scss/base/_globla-variables.scss
> +$theme_root: '/sites/all/themes/custom/f5_psul';
this probably isn't used :)

2024-02-15 18:22 UTC, whereismyjetpack commented
mv to legacy scss directory

2024-02-16 14:41 UTC, schwent commented
Made some file additions

2024-02-16 14:43 UTC, whereismyjetpack commented on scss/style.scss
> +@import "base/*";
```suggestion
@import "base/*";
@import "layout/*";
```

2024-04-19 12:34 UTC, schwent commented
@zipymonkey and @whereismyjetpack - this is really old, and I think we've moved way passed this. Should I close it?

2024-05-21 11:40 UTC, closed without merging